"""Add homie dong in homie history

Revision ID: 337a84764bad
Revises: ab97fad5f07c
Create Date: 2025-05-08 14:15:37.644591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '337a84764bad'
down_revision: Union[str, None] = 'ab97fad5f07c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Homie_histories', sa.Column('homie_dong_id', sa.SmallInteger(), nullable=False))
    op.create_foreign_key(None, 'Homie_histories', 'Homie_dongs', ['homie_dong_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Homie_histories', type_='foreignkey')
    op.drop_column('Homie_histories', 'homie_dong_id')
    # ### end Alembic commands ###
