"""Delete Homie dong in homie history

Revision ID: 368da79197ae
Revises: 79ba3928246c
Create Date: 2025-05-16 12:15:51.848210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '368da79197ae'
down_revision: Union[str, None] = '79ba3928246c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Homie_indicator_descriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('homie_history_id', sa.Integer(), nullable=False),
    sa.Column('indicator', sa.String(length=2), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['homie_history_id'], ['Homie_histories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Homie_indicator_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Homie_indicator_description',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('homie_history_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('indicator', mysql.VARCHAR(length=2), nullable=False),
    sa.ForeignKeyConstraint(['homie_history_id'], ['Homie_histories.id'], name='Homie_indicator_description_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Homie_indicator_descriptions')
    # ### end Alembic commands ###
