"""Update Homie Strong Indicator Table

Revision ID: 381cacf3e5b3
Revises: 7ed736cda692
Create Date: 2025-05-16 17:42:50.125779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '381cacf3e5b3'
down_revision: Union[str, None] = '7ed736cda692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Homie_questions', 'main_category',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=2),
               existing_nullable=False)
    op.add_column('Homie_strong_indicators', sa.Column('main_category', sa.String(length=2), nullable=False))
    op.add_column('Homie_strong_indicators', sa.Column('sub_category', sa.String(length=10), nullable=False))
    op.drop_column('Homie_strong_indicators', 'indicator')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Homie_strong_indicators', sa.Column('indicator', mysql.VARCHAR(length=2), nullable=False))
    op.drop_column('Homie_strong_indicators', 'sub_category')
    op.drop_column('Homie_strong_indicators', 'main_category')
    op.alter_column('Homie_questions', 'main_category',
               existing_type=sa.String(length=2),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
