"""Delete Homie dong in homie history

Revision ID: 79ba3928246c
Revises: b716c6ba12f5
Create Date: 2025-05-16 12:01:03.253274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '79ba3928246c'
down_revision: Union[str, None] = 'b716c6ba12f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Homie_histories_ibfk_1', 'Homie_histories', type_='foreignkey')
    op.drop_column('Homie_histories', 'homie_dong_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Homie_histories', sa.Column('homie_dong_id', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False))
    op.create_foreign_key('Homie_histories_ibfk_1', 'Homie_histories', 'Homie_dongs', ['homie_dong_id'], ['id'])
    # ### end Alembic commands ###
