"""Create homie indicator description

Revision ID: a9be265ae3f7
Revises: cc7fa7a40b4d
Create Date: 2025-05-16 11:32:56.622933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9be265ae3f7'
down_revision: Union[str, None] = 'cc7fa7a40b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Homie_indicator_description',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('homie_history_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['homie_history_id'], ['Homie_histories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Homie_histories', sa.Column('intro_text', sa.TEXT(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Homie_histories', 'intro_text')
    op.drop_table('Homie_indicator_description')
    # ### end Alembic commands ###
