"""Add homie dong

Revision ID: ab97fad5f07c
Revises: de833fc0ebfe
Create Date: 2025-05-07 16:09:28.421776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab97fad5f07c'
down_revision: Union[str, None] = 'de833fc0ebfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Homie_dongs',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('district', sa.String(length=4), nullable=False),
    sa.Column('dong', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Homie_dongs')
    # ### end Alembic commands ###
