"""Add indicator

Revision ID: b716c6ba12f5
Revises: a9be265ae3f7
Create Date: 2025-05-16 11:40:38.150838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b716c6ba12f5'
down_revision: Union[str, None] = 'a9be265ae3f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Homie_indicator_description', sa.Column('indicator', sa.String(length=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Homie_indicator_description', 'indicator')
    # ### end Alembic commands ###
