"""develop homie history model

Revision ID: cc7fa7a40b4d
Revises: ffcb920e4b71
Create Date: 2025-05-16 11:07:16.559317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc7fa7a40b4d'
down_revision: Union[str, None] = 'ffcb920e4b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Homie_history_recommended_dongs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('homie_history_id', sa.Integer(), nullable=False),
    sa.Column('homie_dong_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['homie_dong_id'], ['Homie_dongs.id'], ),
    sa.ForeignKeyConstraint(['homie_history_id'], ['Homie_histories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Homie_recommended_dong_descriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('homie_history_recommended_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['homie_history_recommended_id'], ['Homie_history_recommended_dongs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Homie_strong_indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('indicator', sa.String(length=2), nullable=False),
    sa.Column('homie_history_recommended_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['homie_history_recommended_id'], ['Homie_history_recommended_dongs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Seoul_rooms', sa.Column('deposit', sa.BigInteger(), nullable=True))
    op.add_column('Seoul_rooms', sa.Column('monthly', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Seoul_rooms', 'monthly')
    op.drop_column('Seoul_rooms', 'deposit')
    op.drop_table('Homie_strong_indicators')
    op.drop_table('Homie_recommended_dong_descriptions')
    op.drop_table('Homie_history_recommended_dongs')
    # ### end Alembic commands ###
